        (() => {
    const menu = [
        ['Destaques da casa', 'Big Topet’s', 22, 'Pão, 2 carnes, 2 ovos, 2 queijos, 2 presuntos, salada, milho e batata palha.'], ['Destaques da casa', 'Topet’s Burg', 26, 'Pão, hambúrguer, bacon, frango, calabresa, ovo, queijo, presunto, salada, milho e batata palha.'], ['Destaques da casa', 'Topet’s Frangão', 26, 'Pão, hambúrguer de frango, toscana de frango, frango, ovo, queijo, presunto, salada, milho e batata palha.'], ['Destaques da casa', 'Super Topet’s', 29, 'Pão, hambúrguer, bacon, frango, calabresa, ovo, filé, salsicha, queijo, presunto, salada, milho e batata palha.'], ['Destaques da casa', 'Mega Topet’s', 34, 'Pão, hambúrguer, bacon, frango, calabresa, ovo, filé, coração, salsicha, queijo, presunto, salada, milho e batata palha.'], ['Destaques da casa', 'Topetudo', 72, 'Pão da casa, 2 hambúrgueres, 2 ovos, 2 salsichas, bacon duplo, frango duplo, calabresa dupla, toscana dupla, coração duplo, filé duplo, queijo duplo, presunto duplo, salada, milho e batata palha.'],
        ['Tradicionais', 'Misto quente', 10, 'Pão, queijo e presunto.'], ['Tradicionais', 'Queijo quente', 10, 'Pão e queijo.'], ['Tradicionais', 'Hambúrguer', 10, 'Pão, hambúrguer, salada, milho, ervilha e batata palha.'], ['Tradicionais', 'X-Burguer', 11, 'Pão, hambúrguer, queijo, presunto, milho, salada e batata palha.'], ['Tradicionais', 'Eggs Burguer', 13, 'Pão, hambúrguer, ovo, queijo, presunto, milho, salada e batata palha.'], ['Tradicionais', 'Americano', 11, 'Pão, ovo, queijo, presunto, milho, salada e batata palha.'],
        ['Cachorro-quente', 'Cachorro quente com bacon', 17, 'Pão, salsicha, bacon, alface, vinagrete, milho e batata palha.'], ['Cachorro-quente', 'Cachorro quente de frango', 17, 'Pão, salsicha, frango desfiado, alface, vinagrete, milho e batata palha.'], ['Cachorro-quente', 'Cachorro quente de carne', 18, 'Pão, salsicha, molho de carne com batata, alface, milho e batata palha.'],
        ['Frango', 'X-Frango', 17, 'Pão, frango desfiado, salada, queijo, presunto, milho e batata palha.'], ['Frango', 'Eggs Frango', 19, 'Pão, frango desfiado, ovo, salada, queijo, presunto, milho e batata palha.'], ['Frango', 'Alasanhado', 22, 'Pão, frango desfiado, hambúrguer, ovo, salada, queijo, presunto, milho e batata palha.'], ['Frango', 'X-Frango com calabresa', 22, 'Pão, frango desfiado, calabresa, salada, queijo, presunto, milho e batata palha.'], ['Frango', 'X-Frango com coração', 25, 'Pão, frango desfiado, coração, salada, queijo, presunto, milho e batata palha.'], ['Frango', 'X-Frango com filé', 25, 'Pão, frango desfiado, filé, salada, queijo, presunto, milho e batata palha.'], ['Frango', 'Frango especial', 25, 'Pão, frango desfiado, bacon, cebola, molho de alho, molho inglês, salada, queijo, presunto, milho e batata palha.'],
        ['Filé de frango', 'X Filé de frango', 18, 'Pão, apresuntado, mussarela, filé de peito de frango em cubo, tomate, milho verde, alface e batata palha.'], ['Filé de frango', 'X Filé frango especial', 24, 'Pão, apresuntado, mussarela, filé de peito de frango em cubo, tomate, milho verde, alface, batata palha e bacon.'], ['Filé de frango', 'Eggs filé de frango', 20, 'Pão, apresuntado, mussarela, filé de peito de frango em cubo, ovo, tomate, milho verde, alface e batata palha.'], ['Filé de frango', 'Eggs filé de frango especial', 26, 'Pão, apresuntado, mussarela, filé de peito de frango em cubo, ovo, tomate, milho verde, alface, batata palha e bacon.'], ['Filé de frango', 'Filé de frango da casa', 28, 'Pão, apresuntado, mussarela, filé de peito de frango em cubo, bacon, ovo, calabresa, tomate, milho verde, alface e batata palha.'],
        ['Calabresa e bacon', 'X-Calabresa', 16, 'Pão, hambúrguer, calabresa, salada, queijo, presunto, milho e batata palha.'], ['Calabresa e bacon', 'Eggs Calabresa', 18, 'Pão, hambúrguer, ovo, calabresa, salada, queijo, presunto, milho e batata palha.'], ['Calabresa e bacon', 'X-Calabresa Toscana', 16, 'Pão, hambúrguer, calabresa toscana, salada, queijo, presunto, milho e batata palha.'], ['Calabresa e bacon', 'Eggs Calabresa Toscana', 18, 'Pão, hambúrguer, calabresa toscana, ovo, salada, queijo, presunto, milho e batata palha.'], ['Calabresa e bacon', 'X-Bacon', 19, 'Pão, hambúrguer, bacon, salada, queijo, presunto, milho e batata palha.'], ['Calabresa e bacon', 'Eggs Bacon', 21, 'Pão, hambúrguer, bacon, ovo, salada, queijo, presunto, milho e batata palha.'], ['Calabresa e bacon', 'X-Bacon com calabresa', 26, 'Pão, hambúrguer, bacon, calabresa, salada, queijo, presunto, milho e batata palha.'],
        ['Filé', 'X-Filé', 22, 'Pão, filé, queijo, presunto, salada, milho e batata palha.'], ['Filé', 'Eggs Filé', 24, 'Pão, filé, ovo, queijo, presunto, salada, milho e batata palha.'], ['Filé', 'Filé especial', 28, 'Pão, filé, bacon, molho de tomate com cebola na chapa, molho inglês, molho de alho na chapa, queijo, presunto, salada, milho e batata palha.'], ['Filé', 'X-Filé com coração', 28, 'Pão, filé, coração, queijo, presunto, salada, milho e batata palha.'], ['Filé', 'X Filé com calabresa', 26, 'Pão, filé, calabresa, queijo, presunto, salada, milho e batata palha.'],
        ['Coração', 'X-Coração', 22, 'Pão, coração de frango, queijo, presunto, salada, milho e batata palha.'], ['Coração', 'Eggs Coração', 24, 'Pão, coração de frango, ovo, queijo, presunto, salada, milho e batata palha.'], ['Coração', 'Coração especial', 28, 'Pão, coração de frango, bacon, molho de tomate com cebola na chapa, molho inglês, molho de alho na chapa, queijo, presunto, salada, milho e batata palha.'], ['Coração', 'X-Coração com calabresa', 28, 'Pão, coração de frango, calabresa, queijo, presunto, salada, milho e batata palha.'],
        ['Picanha e especiais', 'X-Picanha', 15, 'Pão, hambúrguer de picanha, mussarela, apresuntado, salada, milho e batata palha.'], ['Picanha e especiais', 'Egg’s Picanha', 17, 'Pão, hambúrguer de picanha, ovo, mussarela, apresuntado, salada, milho e batata palha.'], ['Picanha e especiais', 'Topet’s Picanha', 32, 'Pão, hambúrguer de picanha, ovo, bacon, frango, calabresa, mussarela, apresuntado, salada, milho e batata palha.'], ['Picanha e especiais', 'Big Picanha', 26, 'Pão, 2 hambúrgueres de picanha, 2 ovos, 2 mussarelas, 2 apresuntados, salada, milho e batata palha.'], ['Picanha e especiais', 'Cheddar Picanha', 29, 'Pão, hambúrguer de picanha, bacon, cheddar, salada, milho e batata palha.'], ['Picanha e especiais', 'Du Sol', 24, 'Pão, carne do sol, coalho, cebola caramelizada, salada, milho e batata palha.'], ['Picanha e especiais', 'Toscana especial', 25, 'Pão, hambúrguer, toscana, bacon, mussarela, apresuntado, cebola caramelizada, salada, milho e batata palha.'], ['Picanha e especiais', 'Topet’s Kids', 20, 'Pão, 2 hambúrgueres, salsicha, mussarela, presunto, salada, milho e batata palha.'], ['Picanha e especiais', 'Hambúrguer de bovino', 25, 'Pão, hambúrguer de bovino, ovo, queijo cheddar, cebola e bacon fatiado.'], ['Picanha e especiais', 'Hambúrguer de cordeiro', 28, 'Pão, hambúrguer de cordeiro, ovo, queijo cheddar, cebola, salada e bacon fatiado.'],
        ['Bebidas', 'Coca-Cola lata', 6], ['Bebidas', 'Coca-Cola Zero lata', 6], ['Bebidas', 'Guaraná lata', 6], ['Bebidas', 'Fanta lata', 6], ['Bebidas', 'Sprite lata', 6], ['Bebidas', 'Guaraná litro', 8], ['Bebidas', 'Coca-Cola litro', 10], ['Bebidas', 'Fanta litro', 10], ['Bebidas', 'Água mineral sem gás', 3], ['Bebidas', 'Água mineral com gás', 4], ['Bebidas', 'H2O', 7], ['Bebidas', 'Café', 3],
        ['Sucos', 'Suco de fruta da época 400 ml sem leite', 7, 'Sabores disponíveis: acerola, umbu, cupuaçu, cajá, ameixa, maracujá, manga, laranja, mangaba, graviola, cacau e goiaba.'], ['Sucos', 'Suco de fruta da época 400 ml com leite', 8, 'Sabores disponíveis: acerola, umbu, cupuaçu, cajá, ameixa, maracujá, manga, laranja, mangaba, graviola, cacau e goiaba.'], ['Sucos', 'Suco jarra 1 litro', 18, 'Sabores disponíveis: acerola, umbu, cupuaçu, cajá, ameixa, maracujá, manga, laranja, mangaba, graviola, cacau e goiaba.'],
        ['Tapiocas', 'Mussarela e manteiga', 12], ['Tapiocas', 'Requeijão cremoso, milho e manteiga', 12], ['Tapiocas', 'Mussarela, milho e manteiga', 13], ['Tapiocas', 'Presunto, mussarela e manteiga', 13], ['Tapiocas', 'Catupiry, mussarela e manteiga', 13], ['Tapiocas', 'Frango, catupiry e manteiga', 18], ['Tapiocas', 'Frango, cheddar, mussarela e manteiga', 20], ['Tapiocas', 'Frango, milho, cheddar e manteiga', 19], ['Tapiocas', 'Carne de sol, catupiry, milho e manteiga', 20], ['Tapiocas', 'Carne de sol, cheddar, mussarela, milho e manteiga', 22], ['Tapiocas', 'Calabresa, catupiry, mussarela, milho e manteiga', 22], ['Tapiocas', 'Calabresa, cheddar, mussarela, milho e manteiga', 22], ['Tapiocas', 'Bacon, catupiry, mussarela, milho e manteiga', 22], ['Tapiocas', 'Bacon, cheddar, mussarela, milho e manteiga', 22], ['Tapiocas', 'Filé, catupiry, mussarela, milho e manteiga', 24], ['Tapiocas', 'Filé, cheddar, mussarela, milho e manteiga', 24], ['Tapiocas', 'Tapioca simples', 10, 'Apenas tapioca.'], ['Tapiocas', 'Tapioca com manteiga', 11], ['Tapiocas', 'Queijo coalho e manteiga', 16], ['Tapiocas', 'Queijo catupiry e manteiga', 12],
        ['Porções', 'Batata frita pequena', 15], ['Porções', 'Batata frita grande', 20], ['Porções', 'Batata frita com bacon e cheddar', 28], ['Porções', 'Batata frita com calabresa e cheddar', 28],
        ['Açaí', 'Açaí 200 ml', 13, 'Escolha até 3 acompanhamentos. Calda grátis.'], ['Açaí', 'Açaí 300 ml', 20, 'Escolha até 3 acompanhamentos. Calda grátis.'], ['Açaí', 'Açaí 500 ml', 25, 'Escolha até 3 acompanhamentos. Calda grátis.'], ['Açaí', 'Açaí 1 litro', 38, 'Escolha até 5 acompanhamentos. Calda grátis.'], ['Açaí', 'Açaí na barca 1 litro', 46, 'Acompanha 7 acompanhamentos.'],
        ['Adicionais', 'Hambúrguer', 5], ['Adicionais', 'Ovo', 3], ['Adicionais', 'Mussarela', 4], ['Adicionais', 'Presunto', 4], ['Adicionais', 'Bacon', 10], ['Adicionais', 'Filé', 12], ['Adicionais', 'Frango', 10], ['Adicionais', 'Coração', 12], ['Adicionais', 'Calabresa', 10], ['Adicionais', 'Cebola', 2], ['Adicionais', 'Hambúrguer de picanha', 8], ['Adicionais', 'Toscana', 8], ['Adicionais', 'Salsicha', 4],
        ['Espetinhos', 'Alcatra', 12], ['Espetinhos', 'Cupim', 12], ['Espetinhos', 'Carne de sol', 12], ['Espetinhos', 'Costela', 10.5], ['Espetinhos', 'Kafta', 10.5], ['Espetinhos', 'Medalhão de carne', 15.5], ['Espetinhos', 'Costela de cordeiro', 12.5], ['Espetinhos', 'Filé de cordeiro', 14], ['Espetinhos', 'Coração de frango', 12], ['Espetinhos', 'Filé de frango', 11], ['Espetinhos', 'Medalhão de frango', 15.5], ['Espetinhos', 'Carne com calabresa', 11], ['Espetinhos', 'Frango com calabresa', 11], ['Espetinhos', 'Carne com frango', 11], ['Espetinhos', 'Filé de suíno', 13], ['Espetinhos', 'Costela suína', 11], ['Espetinhos', 'Toscana', 10], ['Espetinhos', 'Queijo coalho', 10], ['Espetinhos', 'Pão de alho', 10],
        ['Pratos e porções', 'Carne do sol com fritas', 45], ['Pratos e porções', 'Cupim na chapa com fritas', 58, 'Acompanha farofa e vinagrete.'], ['Pratos e porções', 'Codorna frita', 15], ['Pratos e porções', 'Tripinha de porco (1 pessoa)', 18], ['Pratos e porções', 'Tripinha de porco (2 pessoas)', 34], ['Pratos e porções', 'Ovos de codorna', 19], ['Pratos e porções', 'Arroz', 6], ['Pratos e porções', 'Vinagrete', 2.5], ['Pratos e porções', 'Pastéis (8 unidades)', 18.9], ['Pratos e porções', 'Macaxeira cozida', 10.5], ['Pratos e porções', 'Macaxeira frita', 17.5], ['Pratos e porções', 'Farofa', 2.5], ['Pratos e porções', 'Cuscuz com calabresa', 18], ['Pratos e porções', 'Cuscuz com filé de frango', 22], ['Pratos e porções', 'Cuscuz com calabresa e coalho', 22], ['Pratos e porções', 'Cuscuz com filé de frango e coalho', 25], ['Pratos e porções', 'Cuscuz com carne de sol', 25, 'Em cubos acebolada e coalho.'], ['Pratos e porções', 'Pastel (unidade)', 9], ['Pratos e porções', 'Batata P.', 15], ['Pratos e porções', 'Batata G.', 20], ['Pratos e porções', 'Batata com bacon e cheddar', 28], ['Pratos e porções', 'Batata com calabresa e cheddar', 28]
    ].map(([category, name, price, description = '']) => ({ id: `${category}-${name}`.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-'), category, name, price, description }));
    const config = { brand: 'Topet’s Lanches', whatsapp: '5579998821022', neighborhoods: [{ name: 'Avenida Quirino', deliveryFeeCents: 300 }, { name: 'São Conrado', deliveryFeeCents: 500 }, { name: 'Orlando', deliveryFeeCents: 500 }, { name: 'Inácio Barbosa', deliveryFeeCents: 600 }, { name: 'Médice', deliveryFeeCents: 600 }, { name: 'Ponto Novo', deliveryFeeCents: 600 }, { name: 'Castelo Branco', deliveryFeeCents: 600 }, { name: 'Jabotiana', deliveryFeeCents: 600 }, { name: 'Augusto Franco', deliveryFeeCents: 700 }, { name: 'Outro (Consultar entrega)', deliveryFeeCents: null, consultDelivery: true }], address: '', hours: '', acaiToppings: ['Banana', 'Amendoim', 'Leite em pó', 'Morango', 'Granola', 'Farinha láctea', 'Kiwi', 'Paçoca', 'Negresco', 'Castanha', 'Confetes', 'Chantilly', 'Ovomaltine', 'Cupuaçu', 'Nutella', 'Gotas de chocolate'], paymentMethods: ['Pix', 'Dinheiro', 'Cartão de crédito', 'Cartão de débito'], addons: menu.filter(item => item.category === 'Adicionais').map(item => ({ name: item.name, price: item.price })) };
    if (typeof module !== 'undefined') module.exports = { menu, config };
    if (typeof window !== 'undefined') { window.menu = menu; window.config = config; }
})();
    



